### ISSUE TITLE
line_segment.vert will not link

### ISSUE THREAD

**Issue by Benoit9** [JuliaGL/GLVisualize.jl#248] opened 2018-03-14 12:08 UTC
GLVisualize 0.7.0
When I run `examples/gui/buttons.jl` or `examples/gui/fractal_lines.jl` I get the error:

> ERROR: LoadError: program 39 not linked. Error in: 
> error: uniform 'thickness' declared as type 'float' and type 'int'

Replacing `{{thickness_type}}` with `uniform float` makes it compile and run fine but I imagine that's not the correct fix. I can't find where `{{thickness_type}}` is interpolated.

**Comment by SimonDanisch** [comment] 2018-03-14 14:45
Hm, you should make sure, that thickness is of type float32... I think I don't have a conversion somewhere, because the thickness can also be a vector

**Comment by Benoit9** [comment] 2018-03-14 15:24
I was only trying to run the unmodified examples. Where is thickness set?

**Comment by SimonDanisch** [comment] 2018-03-14 16:03
can you checkout master? I can't reproduce!

**Comment by SimonDanisch** [comment] 2018-03-14 16:04
Or just update... latest master is also the latest tag!

**Comment by Benoit9** [comment] 2018-03-15 07:15
I am running Julia 0.6.2 binary distribution on Ubuntu 16.04

I moved aside the .julia directory and did a fresh Pkg.add("GLVisualize"), then from the command line:

`julia .julia/v0.6/GLVisualize/examples/gui/buttons.jl` 

and I get the same error:

> ERROR: LoadError: program 37 not linked. Error in: 
> /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/fragment_output.frag or /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/util.vert or /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/line_segment.vert or /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/line_segment.geom or /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/lines.frag
> error: uniform 'thickness' declared as type 'float' and type 'int'

**Comment by Benoit9** [comment] 2018-03-15 08:24
I added a print statement in `GLAbstraction/src/GLShader:gl_convert` in the loop before `compile_program`

Here is the culprit:

`shader 3 /home/x/.julia/v0.6/GLVisualize/src/../assets/shader/line_segment.vert Dict("GLSL_EXTENSIONS"=>"#extension GL_ARB_conservative_depth: enable","thickness_type"=>"uniform int","color_type"=>"uniform vec4","GLSL_VERSION"=>"#version 450\n","color_calculation"=>"color;","vertex_type"=>"in vec2")`

while in the corresponding `line_segment.geom` shader we have:
`uniform float thickness;` (no template parameter there)

**Comment by Benoit9** [comment] 2018-03-15 08:42
OK I found where thickness is passed in as int.

At the end of `src/containers.jl` it should be

`    line_vis = visualize(
        lines, :linesegment, thickness = Float32(0.25mm),
        color = RGBA{Float32}(0.9, 0.9, 0.9, 1.0)
    )`

Sorry for the multiple comments, I am discovering the codebase.

**Comment by SimonDanisch** [comment] 2018-03-29 15:58
should be fixed: https://github.com/JuliaLang/julia/pull/24890

**Closed by SimonDanisch** 2018-03-29 15:58 UTC
